# Generated by Django 6.0.4 on 2026-05-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
    ]
