# Generated by Django 6.0.4 on 2026-05-13 14:07

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=encrypted_fields.fields.EncryptedTextField(verbose_name='description'),
        ),
    ]
