# Generated by Django 6.0.4 on 2026-06-19 23:36

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_remove_friend_unique_friendship_alter_friend_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend',
            name='unique_friendship',
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('first_friend', 'second_friend'), django.db.models.functions.comparison.Greatest('first_friend', 'second_friend'), name='unique_friendship'),
        ),
    ]
