# Generated by Django 6.0.4 on 2026-05-05 18:15

import django.core.validators
import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', encrypted_fields.fields.EncryptedCharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Il numero della carta deve avere 16 cifre', regex='^\\d{16}$')], verbose_name='number')),
                ('name', encrypted_fields.fields.EncryptedCharField(max_length=50, verbose_name='name')),
                ('number_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('expiration_date', models.DateField(verbose_name='expiration_date')),
            ],
            options={
                'verbose_name': 'CreditCard',
                'verbose_name_plural': 'CreditCards',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='credit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='movement')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='WalletCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='wallet.creditcard', verbose_name='credit_card')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='wallet.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'WalletCard',
                'verbose_name_plural': 'WalletCards',
                'constraints': [models.UniqueConstraint(fields=('credit_card', 'wallet'), name='unique_card_wallet')],
            },
        ),
    ]
