# Generated by Django 6.0.4 on 2026-05-30 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_user_remove_cartitem_unique_cart_game_and_more'),
        ('games', '0003_alter_game_release_date_alter_gameimage_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.RemoveConstraint(
            model_name='library',
            name='unique_in_library_game',
        ),
        migrations.AddField(
            model_name='library',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='cart.collection', verbose_name='collection'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('user', 'game', 'collection'), name='unique_in_library_game'),
        ),
    ]
