# Generated by Django 6.0.4 on 2026-06-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_nome_to_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(verbose_name='name'),
        ),
    ]
