# Generated by Django 6.0.4 on 2026-06-17 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_date'),
        ('games', '0003_alter_game_release_date_alter_gameimage_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='library',
            name='unique_in_library_game',
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_in_library_game'),
        ),
    ]
