# Generated by Django 6.0.4 on 2026-05-12 09:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0003_alter_game_release_date_alter_gameimage_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'La minima valutazione è 1 stella'), django.core.validators.MaxValueValidator(5, 'La massima valutazione è 5 stelle')], verbose_name='stars')),
                ('comment', models.TextField(max_length=500, verbose_name='comment')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game', verbose_name='game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'constraints': [models.UniqueConstraint(fields=('user', 'game', 'date'), name='unique_instant_comment')],
            },
        ),
    ]
