import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav>
          <ul className="flex items-center w-full">
            <li><a href="/"><Image src="/favicon.ico" alt="VGShop Logo" width={32} height={32} /></a></li>
            <li><a href="/">Home</a></li>
            <li><a href="/explore">Esplora</a></li>
            <li><a href="/library">Libreria</a></li>
            <li className="ml-auto"><a href="/account">Account</a></li>
          </ul>
        </nav>
        <main>
          {children}
        </main>
        <footer className="mt-auto bg-zinc-200 dark:bg-zinc-800">
          <p className="text-center text-sm text-zinc-500 dark:text-zinc-400">
            &copy; 2023 VGShop. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
