# Generated by Django 6.0.4 on 2026-05-13 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_family_code_family_unique_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='family',
            name='unique_code',
        ),
        migrations.RemoveConstraint(
            model_name='family',
            name='unique_manager',
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.UniqueConstraint(fields=('code', 'manager'), name='unique_code'),
        ),
    ]
