# Generated by Django 6.0.4 on 2026-05-13 14:13

import django.db.models.deletion
import family.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_remove_family_unique_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='family',
            name='unique_code',
        ),
        migrations.AlterField(
            model_name='family',
            name='code',
            field=models.CharField(default=family.models.generate_family_code, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_manager', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
