# Generated by Django 6.0.4 on 2026-04-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='game_images/covers/default.png', upload_to='game_images/covers', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to='game_images/content', verbose_name='game_image'),
        ),
    ]
