# Generated by Django 6.0.4 on 2026-04-28 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_cover_alter_gameimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(verbose_name='release_date'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='games.game', verbose_name='game'),
        ),
    ]
