# Generated by Django 6.0.4 on 2026-04-21 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20260421_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='piva',
            field=models.CharField(blank=True, help_text="Codice di 11 cifre numeriche identificativo dell'azienda o della persona", max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La partita iva deve essere composta da 11 cifre numeriche', regex='^\\d{11}$')], verbose_name='Partita Iva'),
        ),
    ]
