# Generated by Django 6.0.4 on 2026-04-23 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_piva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='piva',
            field=models.CharField(blank=True, help_text="Codice di 11 cifre numeriche identificativo dell'azienda o della persona", max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='VET Number must consists of 11 digits', regex='^\\d{11}$')], verbose_name='Partita Iva'),
        ),
    ]
