# Generated by Django 6.0.4 on 2026-05-27 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iban',
            field=models.CharField(blank=True, help_text='Iban in formato europeo', null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Iban deve seguire lo standard europeo', regex='^[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}$')], verbose_name='Iban'),
        ),
    ]
